#ifndef NET_HTTP2_SVR_TYPES_H_INCLEDED
#define NET_HTTP2_SVR_TYPES_H_INCLEDED
#include "net_system.h"

NET_BEGIN_DECL

typedef struct net_http2_svr_service * net_http2_svr_service_t;
typedef struct net_http2_svr_session * net_http2_svr_session_t;
typedef struct net_http2_svr_stream * net_http2_svr_stream_t;
typedef struct net_http2_svr_request * net_http2_svr_request_t;
typedef struct net_http2_svr_request_header * net_http2_svr_request_header_t;
typedef struct net_http2_svr_request_header_it * net_http2_svr_request_header_it_t;
typedef struct net_http2_svr_response * net_http2_svr_response_t;
typedef struct net_http2_svr_mount_point * net_http2_svr_mount_point_t;
typedef struct net_http2_svr_processor * net_http2_svr_processor_t;

typedef enum net_http2_svr_request_method net_http2_svr_request_method_t;
typedef enum net_http2_svr_request_transfer_encoding net_http2_svr_request_transfer_encoding_t;
typedef enum net_http2_svr_request_state net_http2_svr_request_state_t;
typedef enum net_http2_svr_response_state net_http2_svr_response_state_t;

NET_END_DECL

#endif
