#ifndef NET_ROUTER_SCHEDULE_H_INCLEDED
#define NET_ROUTER_SCHEDULE_H_INCLEDED
#include "net_router_types.h"

NET_BEGIN_DECL

net_router_schedule_t net_router_schedule_create(mem_allocrator_t alloc, error_monitor_t em, net_schedule_t net_schedule);
void net_router_schedule_free(net_router_schedule_t schedule);

mem_allocrator_t net_router_schedule_allocrator(net_router_schedule_t schedule);
error_monitor_t net_router_schedule_em(net_router_schedule_t schedule);
mem_buffer_t net_router_schedule_tmp_buffer(net_router_schedule_t schedule);

net_address_matcher_t net_router_schedule_direct_matcher_white(net_router_schedule_t schedule);
net_address_matcher_t net_router_schedule_direct_matcher_white_check_create(net_router_schedule_t schedule);

net_address_matcher_t net_router_schedule_direct_matcher_black(net_router_schedule_t schedule);
net_address_matcher_t net_router_schedule_direct_matcher_black_check_create(net_router_schedule_t schedule);

uint8_t net_router_schedule_debug(net_router_schedule_t schedule);
    
int net_router_schedule_auto_select(net_router_schedule_t schedule, net_endpoint_t endpoint, net_address_t target_addr, uint8_t is_own);

NET_END_DECL

#endif
