#ifndef NET_HTTP2_STREAM_ENDPOINT_H_INCLEDED
#define NET_HTTP2_STREAM_ENDPOINT_H_INCLEDED
#include "net_http2_types.h"

NET_BEGIN_DECL

net_http2_stream_endpoint_t
net_http2_stream_endpoint_create(
    net_http2_stream_driver_t driver, net_protocol_t protocol);

net_http2_stream_endpoint_t net_http2_stream_endpoint_cast(net_endpoint_t base_endpoint);

net_http2_endpoint_t net_http2_stream_endpoint_http2_ep(net_http2_stream_endpoint_t endpoint);
net_endpoint_t net_http2_stream_endpoint_base_endpoint(net_http2_stream_endpoint_t endpoint);

net_http2_req_t net_http2_stream_endpoint_req(net_http2_stream_endpoint_t endpoint);

net_http2_endpoint_runing_mode_t net_http2_stream_endpoint_runing_mode(net_http2_stream_endpoint_t endpoint);

NET_END_DECL

#endif
